"""update_spider_files

Revision ID: af6506912ce5
Revises: 21ca62323acd
Create Date: 2026-01-31 13:27:18.342763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.crawlhub.spider import ProjectType
from models.crawlhub.spider import ScriptType
from models.crawlhub.task import SpiderTaskStatus
from sqlalchemy.dialects import postgresql
import models

# revision identifiers, used by Alembic.
revision: str = 'af6506912ce5'
down_revision: Union[str, Sequence[str], None] = '21ca62323acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawlhub_spider_files',
    sa.Column('spider_id', models.types.StringUUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件相对路径'),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='存储Key'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME类型'),
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('crawlhub_spider_files_pkey'))
    )
    op.add_column('crawlhub_spiders', sa.Column('project_type', models.types.EnumText(ProjectType), nullable=False, comment='项目类型'))
    op.add_column('crawlhub_spiders', sa.Column('entry_point', sa.String(length=255), nullable=True, comment='入口点'))
    op.alter_column('crawlhub_spiders', 'script_type',
               existing_type=postgresql.ENUM('HTTPX', 'SCRAPY', 'PLAYWRIGHT', name='scripttype'),
               type_=models.types.EnumText(ScriptType),
               existing_comment='脚本类型',
               existing_nullable=False)
    op.drop_constraint(op.f('crawlhub_spiders_project_id_fkey'), 'crawlhub_spiders', type_='foreignkey')
    op.add_column('crawlhub_tasks', sa.Column('is_test', sa.Boolean(), nullable=False, comment='是否为测试运行'))
    op.alter_column('crawlhub_tasks', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               type_=models.types.EnumText(SpiderTaskStatus),
               existing_comment='任务状态',
               existing_nullable=False)
    op.drop_constraint(op.f('crawlhub_tasks_spider_id_fkey'), 'crawlhub_tasks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('crawlhub_tasks_spider_id_fkey'), 'crawlhub_tasks', 'crawlhub_spiders', ['spider_id'], ['id'], ondelete='CASCADE')
    op.alter_column('crawlhub_tasks', 'status',
               existing_type=models.types.EnumText(SpiderTaskStatus),
               type_=postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'),
               existing_comment='任务状态',
               existing_nullable=False)
    op.drop_column('crawlhub_tasks', 'is_test')
    op.create_foreign_key(op.f('crawlhub_spiders_project_id_fkey'), 'crawlhub_spiders', 'crawlhub_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('crawlhub_spiders', 'script_type',
               existing_type=models.types.EnumText(ScriptType),
               type_=postgresql.ENUM('HTTPX', 'SCRAPY', 'PLAYWRIGHT', name='scripttype'),
               existing_comment='脚本类型',
               existing_nullable=False)
    op.drop_column('crawlhub_spiders', 'entry_point')
    op.drop_column('crawlhub_spiders', 'project_type')
    op.drop_table('crawlhub_spider_files')
    # ### end Alembic commands ###
