"""init

Revision ID: bff4377e06db
Revises:
Create Date: 2026-01-12 17:40:30.498732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.task import TaskStatus
from models.task import TaskType
from sqlalchemy.dialects import postgresql
import models

# revision identifiers, used by Alembic.
revision: str = "bff4377e06db"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_integrates",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("account_id", models.types.StringUUID(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("open_id", sa.String(length=255), nullable=False),
        sa.Column("encrypted_token", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="account_integrate_pkey"),
        sa.UniqueConstraint("account_id", "provider", name="unique_account_provider"),
        sa.UniqueConstraint("provider", "open_id", name="unique_provider_open_id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("password_salt", sa.String(length=255), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("interface_language", sa.String(length=255), nullable=True),
        sa.Column("timezone", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(length=255), nullable=True),
        sa.Column(
            "last_active_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("initialized_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="account_pkey"),
    )
    op.create_index("account_email_idx", "accounts", ["email"], unique=False)
    op.create_table(
        "admins",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("password_salt", sa.String(length=255), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("interface_language", sa.String(length=255), nullable=True),
        sa.Column("timezone", sa.String(length=255), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(length=255), nullable=True),
        sa.Column(
            "last_active_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("initialized_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="admin_pkey"),
    )
    op.create_table(
        "api_based_extensions",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column(
            "tenant_id",
            models.types.StringUUID(),
            server_default="ffffffff-ffff-ffff-ffff-ffffffffffff",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("api_endpoint", sa.String(length=255), nullable=False),
        sa.Column("api_key", models.types.LongText(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="api_based_extension_pkey"),
    )
    op.create_index(
        "api_based_extension_tenant_idx", "api_based_extensions", ["tenant_id"], unique=False
    )
    op.create_table(
        "api_keys",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=True),
        sa.Column("created_by", models.types.StringUUID(), nullable=True),
        sa.Column("whitelist", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("rph", sa.Integer(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="api_key_pkey"),
    )
    op.create_index("api_key_key_hash_idx", "api_keys", ["key_hash"], unique=True)
    op.create_index("api_key_key_prefix_idx", "api_keys", ["key_prefix"], unique=False)
    op.create_index("api_key_status_idx", "api_keys", ["status"], unique=False)
    op.create_index("api_key_tenant_id_idx", "api_keys", ["tenant_id"], unique=False)
    op.create_table(
        "api_usage_logs",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("api_key_id", models.types.StringUUID(), nullable=False),
        sa.Column("endpoint", sa.String(length=256), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("service_type", sa.String(length=32), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_message", models.types.LongText(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="api_usage_log_pkey"),
    )
    op.create_index("api_usage_log_api_key_id_idx", "api_usage_logs", ["api_key_id"], unique=False)
    op.create_index("api_usage_log_created_at_idx", "api_usage_logs", ["created_at"], unique=False)
    op.create_index("api_usage_log_endpoint_idx", "api_usage_logs", ["endpoint"], unique=False)
    op.create_index(
        "api_usage_log_service_type_idx", "api_usage_logs", ["service_type"], unique=False
    )
    op.create_index("api_usage_log_tenant_id_idx", "api_usage_logs", ["tenant_id"], unique=False)
    op.create_table(
        "balance_logs",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("account_id", models.types.StringUUID(), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("balance_before", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("related_order_id", models.types.StringUUID(), nullable=True),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("operator_id", models.types.StringUUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="balance_log_pkey"),
    )
    op.create_index("balance_log_tenant_id_idx", "balance_logs", ["tenant_id"], unique=False)
    op.create_index("balance_log_type_idx", "balance_logs", ["type"], unique=False)
    op.create_table(
        "child_chunks",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("document_id", models.types.StringUUID(), nullable=False),
        sa.Column("segment_id", models.types.StringUUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", models.types.LongText(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("index_node_id", sa.String(length=255), nullable=True),
        sa.Column("index_node_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "type", sa.String(length=255), server_default=sa.text("'automatic'"), nullable=False
        ),
        sa.Column("created_by", models.types.StringUUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("updated_by", models.types.StringUUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("indexing_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error", models.types.LongText(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="child_chunk_pkey"),
    )
    op.create_index("child_chunks_node_idx", "child_chunks", ["index_node_id"], unique=False)
    op.create_index("child_chunks_segment_idx", "child_chunks", ["segment_id"], unique=False)
    op.create_index(
        "tenant_id", "child_chunks", ["document_id", "segment_id", "index_node_id"], unique=False
    )
    op.create_table(
        "document_segments",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("document_id", models.types.StringUUID(), nullable=False),
        sa.Column("content", models.types.LongText(), nullable=False),
        sa.Column("answer", models.types.LongText(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("index_node_id", sa.String(length=255), nullable=True),
        sa.Column("index_node_hash", sa.String(length=255), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("disabled_at", sa.DateTime(), nullable=True),
        sa.Column("disabled_by", models.types.StringUUID(), nullable=True),
        sa.Column(
            "status", sa.String(length=255), server_default=sa.text("'waiting'"), nullable=False
        ),
        sa.Column("created_by", models.types.StringUUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("updated_by", models.types.StringUUID(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("indexing_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error", models.types.LongText(), nullable=True),
        sa.Column("stopped_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="document_segment_pkey"),
    )
    op.create_index(
        "document_segment_document_id_idx", "document_segments", ["document_id"], unique=False
    )
    op.create_index(
        "document_segment_tenant_document_idx",
        "document_segments",
        ["document_id", "tenant_id"],
        unique=False,
    )
    op.create_index("document_segment_tenant_idx", "document_segments", ["tenant_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("data_source_type", sa.String(length=255), nullable=False),
        sa.Column("data_source_info", models.types.LongText(), nullable=True),
        sa.Column("batch", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_from", sa.String(length=255), nullable=False),
        sa.Column("created_by", models.types.StringUUID(), nullable=False),
        sa.Column("created_api_request_id", models.types.StringUUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("processing_started_at", sa.DateTime(), nullable=True),
        sa.Column("file_id", models.types.LongText(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("parsing_completed_at", sa.DateTime(), nullable=True),
        sa.Column("cleaning_completed_at", sa.DateTime(), nullable=True),
        sa.Column("splitting_completed_at", sa.DateTime(), nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("indexing_latency", sa.Float(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("is_paused", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("paused_by", models.types.StringUUID(), nullable=True),
        sa.Column("paused_at", sa.DateTime(), nullable=True),
        sa.Column("error", models.types.LongText(), nullable=True),
        sa.Column("stopped_at", sa.DateTime(), nullable=True),
        sa.Column(
            "indexing_status",
            sa.String(length=255),
            server_default=sa.text("'waiting'"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("disabled_at", sa.DateTime(), nullable=True),
        sa.Column("disabled_by", models.types.StringUUID(), nullable=True),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("archived_by", models.types.StringUUID(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("doc_type", sa.String(length=40), nullable=True),
        sa.Column("doc_metadata", models.types.AdjustedJSON(), nullable=True),
        sa.Column(
            "doc_form",
            sa.String(length=255),
            server_default=sa.text("'text_model'"),
            nullable=False,
        ),
        sa.Column("doc_language", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name="document_pkey"),
    )
    op.create_index("document_is_paused_idx", "documents", ["is_paused"], unique=False)
    op.create_index(
        "document_metadata_idx", "documents", ["doc_metadata"], unique=False, postgresql_using="gin"
    )
    op.create_index("document_tenant_idx", "documents", ["tenant_id"], unique=False)
    op.create_table(
        "fastapi_setups",
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column(
            "setup_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("version", name="fastapi_setup_pkey"),
    )
    op.create_table(
        "invitation_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'unused'"), nullable=False
        ),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("used_by_tenant_id", models.types.StringUUID(), nullable=True),
        sa.Column("used_by_account_id", models.types.StringUUID(), nullable=True),
        sa.Column("deprecated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="invitation_code_pkey"),
    )
    op.create_index("invitation_codes_batch_idx", "invitation_codes", ["batch"], unique=False)
    op.create_index(
        "invitation_codes_code_idx", "invitation_codes", ["code", "status"], unique=False
    )
    op.create_table(
        "oauth_provider_apps",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("app_icon", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret", sa.String(length=255), nullable=False),
        sa.Column("app_label", sa.JSON(), nullable=False),
        sa.Column("redirect_uris", sa.JSON(), nullable=False),
        sa.Column(
            "scope",
            sa.String(length=255),
            server_default=sa.text(
                "'read:name read:email read:avatar read:interface_language read:timezone'"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="oauth_provider_app_pkey"),
    )
    op.create_index(
        "oauth_provider_app_client_id_idx", "oauth_provider_apps", ["client_id"], unique=False
    )
    op.create_table(
        "pending_plan_changes",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("current_plan", sa.String(length=32), nullable=False),
        sa.Column("target_plan", sa.String(length=32), nullable=False),
        sa.Column("target_billing_cycle", sa.String(length=16), nullable=False),
        sa.Column("effective_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pending_plan_change_pkey"),
        sa.UniqueConstraint("tenant_id", name=op.f("pending_plan_changes_tenant_id_key")),
    )
    op.create_index(
        "pending_plan_change_status_idx", "pending_plan_changes", ["status"], unique=False
    )
    op.create_index(
        "pending_plan_change_tenant_id_idx", "pending_plan_changes", ["tenant_id"], unique=False
    )
    op.create_table(
        "proxy_routes",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column(
            "path",
            sa.String(length=512),
            nullable=False,
            comment="Route path pattern to match incoming requests",
        ),
        sa.Column(
            "target_urls",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
            comment="Target URLs for load balancing or failover",
        ),
        sa.Column(
            "load_balance_mode",
            sa.String(length=32),
            nullable=False,
            comment="Load balance mode: round_robin or failover",
        ),
        sa.Column(
            "methods",
            sa.String(length=128),
            nullable=False,
            comment="Allowed HTTP methods, comma-separated or * for all",
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            comment="Route status: enabled or disabled",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Route description"),
        sa.Column("timeout", sa.Integer(), nullable=False, comment="Request timeout in seconds"),
        sa.Column(
            "preserve_host",
            sa.Boolean(),
            nullable=False,
            comment="Whether to preserve the original Host header",
        ),
        sa.Column(
            "enable_logging",
            sa.Boolean(),
            nullable=False,
            comment="Whether to log requests for this route",
        ),
        sa.Column(
            "streaming",
            sa.Boolean(),
            nullable=False,
            comment="Whether to use streaming mode for responses (recommended for SSE/large files)",
        ),
        sa.Column(
            "created_by",
            models.types.StringUUID(),
            nullable=True,
            comment="Admin user ID who created this route",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="proxy_route_pkey"),
        sa.UniqueConstraint("path", name="proxy_route_path_key"),
    )
    op.create_index("proxy_route_created_at_idx", "proxy_routes", ["created_at"], unique=False)
    op.create_index("proxy_route_status_idx", "proxy_routes", ["status"], unique=False)
    op.create_table(
        "recharge_orders",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("account_id", models.types.StringUUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payment_method", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trade_no", sa.String(length=64), nullable=True),
        sa.Column("out_trade_no", sa.String(length=64), nullable=False),
        sa.Column("qr_code_url", sa.Text(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="recharge_order_pkey"),
    )
    op.create_index("recharge_order_status_idx", "recharge_orders", ["status"], unique=False)
    op.create_index("recharge_order_tenant_id_idx", "recharge_orders", ["tenant_id"], unique=False)
    op.create_index("recharge_order_trade_no_idx", "recharge_orders", ["trade_no"], unique=False)
    op.create_table(
        "subscription_orders",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("account_id", models.types.StringUUID(), nullable=True),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("billing_cycle", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_auto_renew", sa.Boolean(), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("original_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("prorated_credit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("previous_plan", sa.String(length=32), nullable=True),
        sa.Column("is_first_month_discount", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="subscription_order_pkey"),
    )
    op.create_index(
        "subscription_order_status_idx", "subscription_orders", ["status"], unique=False
    )
    op.create_index(
        "subscription_order_tenant_id_idx", "subscription_orders", ["tenant_id"], unique=False
    )
    op.create_index(
        "subscription_order_type_idx", "subscription_orders", ["order_type"], unique=False
    )
    op.create_table(
        "subscription_plans",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("price_monthly", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("price_yearly", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Integer(), nullable=False),
        sa.Column("first_month_discount_percent", sa.Integer(), nullable=False),
        sa.Column("first_month_discount_enabled", sa.Boolean(), nullable=False),
        sa.Column("team_members", sa.Integer(), nullable=False),
        sa.Column("apps_limit", sa.Integer(), nullable=False),
        sa.Column("api_rate_limit", sa.Integer(), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="subscription_plan_pkey"),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("key", name="system_setting_pkey"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=False, comment="Celery任务ID"),
        sa.Column("task_type", models.types.EnumText(TaskType), nullable=False, comment="任务类型"),
        sa.Column("task_name", sa.String(length=255), nullable=False, comment="任务名称"),
        sa.Column("status", models.types.EnumText(TaskStatus), nullable=False, comment="任务状态"),
        sa.Column(
            "priority", sa.Integer(), nullable=False, comment="任务优先级(0-15,数值越大优先级越高)"
        ),
        sa.Column(
            "params",
            sa.Text(),
            nullable=True,
            comment='任务参数(JSON格式: {"args": [...], "kwargs": {...}})',
        ),
        sa.Column("result", sa.Text(), nullable=True, comment="任务结果(JSON)"),
        sa.Column("error", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column("traceback", sa.Text(), nullable=True, comment="错误堆栈"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True, comment="开始时间"),
        sa.Column("completed_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("duration", sa.Integer(), nullable=True, comment="任务耗时(秒)"),
        sa.Column("user_id", sa.UUID(), nullable=True, comment="用户ID"),
        sa.Column("progress", sa.Integer(), nullable=False, comment="任务进度(0-100)"),
        sa.Column("retry_count", sa.Integer(), nullable=False, comment="重试次数"),
        sa.Column("max_retries", sa.Integer(), nullable=False, comment="最大重试次数"),
        sa.PrimaryKeyConstraint("id", name="task_pkey"),
    )
    op.create_index("task_created_at_idx", "tasks", ["created_at"], unique=False)
    op.create_index("task_priority_idx", "tasks", ["priority"], unique=False)
    op.create_index("task_priority_status_idx", "tasks", ["priority", "status"], unique=False)
    op.create_index("task_status_idx", "tasks", ["status"], unique=False)
    op.create_index("task_task_id_idx", "tasks", ["task_id"], unique=False)
    op.create_index("task_task_type_idx", "tasks", ["task_type"], unique=False)
    op.create_table(
        "tenant_account_joins",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=False),
        sa.Column("account_id", models.types.StringUUID(), nullable=False),
        sa.Column("current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="normal", nullable=False),
        sa.Column("invited_by", models.types.StringUUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="tenant_account_join_pkey"),
        sa.UniqueConstraint("tenant_id", "account_id", name="unique_tenant_account_join"),
    )
    op.create_index(
        "tenant_account_join_account_id_idx", "tenant_account_joins", ["account_id"], unique=False
    )
    op.create_index(
        "tenant_account_join_tenant_id_idx", "tenant_account_joins", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("encrypt_public_key", models.types.LongText(), nullable=True),
        sa.Column("plan", sa.String(length=255), server_default=sa.text("'basic'"), nullable=False),
        sa.Column(
            "status", sa.String(length=255), server_default=sa.text("'normal'"), nullable=False
        ),
        sa.Column("custom_config", models.types.LongText(), nullable=True),
        sa.Column(
            "balance",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("plan_expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="tenant_pkey"),
    )
    op.create_table(
        "upload_files",
        sa.Column("id", models.types.StringUUID(), nullable=False),
        sa.Column("tenant_id", models.types.StringUUID(), nullable=True),
        sa.Column("storage_type", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("extension", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("created_by_role", sa.String(length=255), nullable=False),
        sa.Column("created_by", models.types.StringUUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("hash", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="upload_file_pkey"),
    )
    op.create_index("upload_file_tenant_idx", "upload_files", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("upload_file_tenant_idx", table_name="upload_files")
    op.drop_table("upload_files")
    op.drop_table("tenants")
    op.drop_index("tenant_account_join_tenant_id_idx", table_name="tenant_account_joins")
    op.drop_index("tenant_account_join_account_id_idx", table_name="tenant_account_joins")
    op.drop_table("tenant_account_joins")
    op.drop_index("task_task_type_idx", table_name="tasks")
    op.drop_index("task_task_id_idx", table_name="tasks")
    op.drop_index("task_status_idx", table_name="tasks")
    op.drop_index("task_priority_status_idx", table_name="tasks")
    op.drop_index("task_priority_idx", table_name="tasks")
    op.drop_index("task_created_at_idx", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("system_settings")
    op.drop_table("subscription_plans")
    op.drop_index("subscription_order_type_idx", table_name="subscription_orders")
    op.drop_index("subscription_order_tenant_id_idx", table_name="subscription_orders")
    op.drop_index("subscription_order_status_idx", table_name="subscription_orders")
    op.drop_table("subscription_orders")
    op.drop_index("recharge_order_trade_no_idx", table_name="recharge_orders")
    op.drop_index("recharge_order_tenant_id_idx", table_name="recharge_orders")
    op.drop_index("recharge_order_status_idx", table_name="recharge_orders")
    op.drop_table("recharge_orders")
    op.drop_index("proxy_route_status_idx", table_name="proxy_routes")
    op.drop_index("proxy_route_created_at_idx", table_name="proxy_routes")
    op.drop_table("proxy_routes")
    op.drop_index("pending_plan_change_tenant_id_idx", table_name="pending_plan_changes")
    op.drop_index("pending_plan_change_status_idx", table_name="pending_plan_changes")
    op.drop_table("pending_plan_changes")
    op.drop_index("oauth_provider_app_client_id_idx", table_name="oauth_provider_apps")
    op.drop_table("oauth_provider_apps")
    op.drop_index("invitation_codes_code_idx", table_name="invitation_codes")
    op.drop_index("invitation_codes_batch_idx", table_name="invitation_codes")
    op.drop_table("invitation_codes")
    op.drop_table("fastapi_setups")
    op.drop_index("document_tenant_idx", table_name="documents")
    op.drop_index("document_metadata_idx", table_name="documents", postgresql_using="gin")
    op.drop_index("document_is_paused_idx", table_name="documents")
    op.drop_table("documents")
    op.drop_index("document_segment_tenant_idx", table_name="document_segments")
    op.drop_index("document_segment_tenant_document_idx", table_name="document_segments")
    op.drop_index("document_segment_document_id_idx", table_name="document_segments")
    op.drop_table("document_segments")
    op.drop_index("tenant_id", table_name="child_chunks")
    op.drop_index("child_chunks_segment_idx", table_name="child_chunks")
    op.drop_index("child_chunks_node_idx", table_name="child_chunks")
    op.drop_table("child_chunks")
    op.drop_index("balance_log_type_idx", table_name="balance_logs")
    op.drop_index("balance_log_tenant_id_idx", table_name="balance_logs")
    op.drop_table("balance_logs")
    op.drop_index("api_usage_log_tenant_id_idx", table_name="api_usage_logs")
    op.drop_index("api_usage_log_service_type_idx", table_name="api_usage_logs")
    op.drop_index("api_usage_log_endpoint_idx", table_name="api_usage_logs")
    op.drop_index("api_usage_log_created_at_idx", table_name="api_usage_logs")
    op.drop_index("api_usage_log_api_key_id_idx", table_name="api_usage_logs")
    op.drop_table("api_usage_logs")
    op.drop_index("api_key_tenant_id_idx", table_name="api_keys")
    op.drop_index("api_key_status_idx", table_name="api_keys")
    op.drop_index("api_key_key_prefix_idx", table_name="api_keys")
    op.drop_index("api_key_key_hash_idx", table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("api_based_extension_tenant_idx", table_name="api_based_extensions")
    op.drop_table("api_based_extensions")
    op.drop_table("admins")
    op.drop_index("account_email_idx", table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("account_integrates")
    # ### end Alembic commands ###
